// <auto-generated />
using System;
using KS.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KS.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "6.0.0-preview.3.21201.2")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("KS.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = "b74ddd14-6340-4840-95c2-db12554843e5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "43d4c7aa-c5a7-45e7-b2c3-a56a1be04c45",
                            Email = "admin@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumber = "1234567890",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "Admin"
                        });
                });

            modelBuilder.Entity("KS.Entities.Brand", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreationDate = new DateTime(2021, 6, 10, 0, 23, 28, 587, DateTimeKind.Local).AddTicks(9629),
                            Description = "Nike",
                            Name = "Nike"
                        },
                        new
                        {
                            Id = 2L,
                            CreationDate = new DateTime(2021, 6, 10, 0, 23, 28, 587, DateTimeKind.Local).AddTicks(9803),
                            Description = "Adidas",
                            Name = "Adidas"
                        },
                        new
                        {
                            Id = 3L,
                            CreationDate = new DateTime(2021, 6, 10, 0, 23, 28, 587, DateTimeKind.Local).AddTicks(9809),
                            Description = "Polo",
                            Name = "Polo"
                        },
                        new
                        {
                            Id = 4L,
                            CreationDate = new DateTime(2021, 6, 10, 0, 23, 28, 587, DateTimeKind.Local).AddTicks(9813),
                            Description = "Balmain",
                            Name = "Balmain"
                        },
                        new
                        {
                            Id = 5L,
                            CreationDate = new DateTime(2021, 6, 10, 0, 23, 28, 587, DateTimeKind.Local).AddTicks(9819),
                            Description = "Bottega Veneta",
                            Name = "Bottega Veneta"
                        },
                        new
                        {
                            Id = 6L,
                            CreationDate = new DateTime(2021, 6, 10, 0, 23, 28, 587, DateTimeKind.Local).AddTicks(9824),
                            Description = "Brunello Cucinelli",
                            Name = "Brunello Cucinelli"
                        },
                        new
                        {
                            Id = 7L,
                            CreationDate = new DateTime(2021, 6, 10, 0, 23, 28, 587, DateTimeKind.Local).AddTicks(9828),
                            Description = "Jil Sander",
                            Name = "Jil Sander"
                        },
                        new
                        {
                            Id = 8L,
                            CreationDate = new DateTime(2021, 6, 10, 0, 23, 28, 587, DateTimeKind.Local).AddTicks(9834),
                            Description = "Gucci",
                            Name = "Gucci"
                        },
                        new
                        {
                            Id = 9L,
                            CreationDate = new DateTime(2021, 6, 10, 0, 23, 28, 587, DateTimeKind.Local).AddTicks(9838),
                            Description = "Ralph Lauren",
                            Name = "Ralph Lauren"
                        },
                        new
                        {
                            Id = 10L,
                            CreationDate = new DateTime(2021, 6, 10, 0, 23, 28, 587, DateTimeKind.Local).AddTicks(9843),
                            Description = "Alexander McQueen",
                            Name = "Alexander McQueen"
                        },
                        new
                        {
                            Id = 11L,
                            CreationDate = new DateTime(2021, 6, 10, 0, 23, 28, 587, DateTimeKind.Local).AddTicks(9848),
                            Description = "Prada",
                            Name = "Prada"
                        },
                        new
                        {
                            Id = 12L,
                            CreationDate = new DateTime(2021, 6, 10, 0, 23, 28, 587, DateTimeKind.Local).AddTicks(9852),
                            Description = "Off-White",
                            Name = "Off-White"
                        },
                        new
                        {
                            Id = 13L,
                            CreationDate = new DateTime(2021, 6, 10, 0, 23, 28, 587, DateTimeKind.Local).AddTicks(9857),
                            Description = "Versace",
                            Name = "Versace"
                        });
                });

            modelBuilder.Entity("KS.Entities.CartItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CartId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("KS.Entities.Category", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreationDate = new DateTime(2021, 6, 10, 0, 23, 28, 590, DateTimeKind.Local).AddTicks(5728),
                            Name = "Блуза",
                            Slug = "Блуза"
                        },
                        new
                        {
                            Id = 2L,
                            CreationDate = new DateTime(2021, 6, 10, 0, 23, 28, 590, DateTimeKind.Local).AddTicks(5751),
                            Name = "Рубашка",
                            Slug = "Рубашка"
                        },
                        new
                        {
                            Id = 3L,
                            CreationDate = new DateTime(2021, 6, 10, 0, 23, 28, 590, DateTimeKind.Local).AddTicks(5756),
                            Name = "Брюки",
                            Slug = "Брюки"
                        },
                        new
                        {
                            Id = 4L,
                            CreationDate = new DateTime(2021, 6, 10, 0, 23, 28, 590, DateTimeKind.Local).AddTicks(5761),
                            Name = "Бриджи",
                            Slug = "Бриджи"
                        },
                        new
                        {
                            Id = 5L,
                            CreationDate = new DateTime(2021, 6, 10, 0, 23, 28, 590, DateTimeKind.Local).AddTicks(5766),
                            Name = "Лосины",
                            Slug = "Лосины"
                        },
                        new
                        {
                            Id = 6L,
                            CreationDate = new DateTime(2021, 6, 10, 0, 23, 28, 590, DateTimeKind.Local).AddTicks(5771),
                            Name = "Джинсы",
                            Slug = "Джинсы"
                        },
                        new
                        {
                            Id = 7L,
                            CreationDate = new DateTime(2021, 6, 10, 0, 23, 28, 590, DateTimeKind.Local).AddTicks(5777),
                            Name = "Шорты",
                            Slug = "Шорты"
                        },
                        new
                        {
                            Id = 8L,
                            CreationDate = new DateTime(2021, 6, 10, 0, 23, 28, 590, DateTimeKind.Local).AddTicks(5784),
                            Name = "Юбка",
                            Slug = "Юбка"
                        },
                        new
                        {
                            Id = 9L,
                            CreationDate = new DateTime(2021, 6, 10, 0, 23, 28, 590, DateTimeKind.Local).AddTicks(5789),
                            Name = "Комбинезон",
                            Slug = "Комбинезон"
                        },
                        new
                        {
                            Id = 10L,
                            CreationDate = new DateTime(2021, 6, 10, 0, 23, 28, 590, DateTimeKind.Local).AddTicks(5794),
                            Name = "Джемпер",
                            Slug = "Джемпер"
                        },
                        new
                        {
                            Id = 11L,
                            CreationDate = new DateTime(2021, 6, 10, 0, 23, 28, 590, DateTimeKind.Local).AddTicks(5799),
                            Name = "Свитер",
                            Slug = "Свитер"
                        },
                        new
                        {
                            Id = 12L,
                            CreationDate = new DateTime(2021, 6, 10, 0, 23, 28, 590, DateTimeKind.Local).AddTicks(5804),
                            Name = "Гольф",
                            Slug = "Гольф"
                        },
                        new
                        {
                            Id = 13L,
                            CreationDate = new DateTime(2021, 6, 10, 0, 23, 28, 590, DateTimeKind.Local).AddTicks(5809),
                            Name = "Пуловер",
                            Slug = "Пуловер"
                        },
                        new
                        {
                            Id = 14L,
                            CreationDate = new DateTime(2021, 6, 10, 0, 23, 28, 590, DateTimeKind.Local).AddTicks(5815),
                            Name = "Кофта",
                            Slug = "Кофта"
                        },
                        new
                        {
                            Id = 15L,
                            CreationDate = new DateTime(2021, 6, 10, 0, 23, 28, 590, DateTimeKind.Local).AddTicks(5820),
                            Name = "Кардиган",
                            Slug = "Кардиган"
                        },
                        new
                        {
                            Id = 16L,
                            CreationDate = new DateTime(2021, 6, 10, 0, 23, 28, 590, DateTimeKind.Local).AddTicks(5825),
                            Name = "Жакет",
                            Slug = "Жакет"
                        },
                        new
                        {
                            Id = 17L,
                            CreationDate = new DateTime(2021, 6, 10, 0, 23, 28, 590, DateTimeKind.Local).AddTicks(5830),
                            Name = "Пиджак",
                            Slug = "Пиджак"
                        },
                        new
                        {
                            Id = 18L,
                            CreationDate = new DateTime(2021, 6, 10, 0, 23, 28, 590, DateTimeKind.Local).AddTicks(5835),
                            Name = "Футболка",
                            Slug = "Футболка"
                        },
                        new
                        {
                            Id = 19L,
                            CreationDate = new DateTime(2021, 6, 10, 0, 23, 28, 590, DateTimeKind.Local).AddTicks(5840),
                            Name = "Майка",
                            Slug = "Майка"
                        },
                        new
                        {
                            Id = 20L,
                            CreationDate = new DateTime(2021, 6, 10, 0, 23, 28, 590, DateTimeKind.Local).AddTicks(5845),
                            Name = "Поло",
                            Slug = "Поло"
                        },
                        new
                        {
                            Id = 21L,
                            CreationDate = new DateTime(2021, 6, 10, 0, 23, 28, 590, DateTimeKind.Local).AddTicks(5850),
                            Name = "Футболка с длинным рукавом",
                            Slug = "Футболка с длинным рукавом"
                        },
                        new
                        {
                            Id = 22L,
                            CreationDate = new DateTime(2021, 6, 10, 0, 23, 28, 590, DateTimeKind.Local).AddTicks(5855),
                            Name = "Тенниска",
                            Slug = "Тенниска"
                        },
                        new
                        {
                            Id = 23L,
                            CreationDate = new DateTime(2021, 6, 10, 0, 23, 28, 590, DateTimeKind.Local).AddTicks(5861),
                            Name = "Реглан",
                            Slug = "Реглан"
                        },
                        new
                        {
                            Id = 24L,
                            CreationDate = new DateTime(2021, 6, 10, 0, 23, 28, 590, DateTimeKind.Local).AddTicks(5866),
                            Name = "Платье",
                            Slug = "Платье"
                        },
                        new
                        {
                            Id = 25L,
                            CreationDate = new DateTime(2021, 6, 10, 0, 23, 28, 590, DateTimeKind.Local).AddTicks(5871),
                            Name = "Ветровка",
                            Slug = "Ветровка"
                        });
                });

            modelBuilder.Entity("KS.Entities.Media", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Caption")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("FileSize")
                        .HasColumnType("int");

                    b.Property<byte>("MediaType")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("KS.Entities.Order", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderRef")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StripeReference")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("KS.Entities.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("BrandId")
                        .HasColumnType("bigint");

                    b.Property<string>("CoverImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("GenderType")
                        .HasColumnType("tinyint");

                    b.Property<bool>("HasOptions")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAllowToOrder")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCallForPricing")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("OldPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("SpecialPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset?>("SpecialPriceEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("SpecialPriceStart")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Specification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<bool>("StockTrackingIsEnabled")
                        .HasColumnType("bit");

                    b.Property<long?>("TaxClassId")
                        .HasColumnType("bigint");

                    b.Property<int>("UnitType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("TaxClassId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("KS.Entities.ProductCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductCategories");
                });

            modelBuilder.Entity("KS.Entities.Stock", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("ReservedQuantity")
                        .HasColumnType("int");

                    b.Property<long>("WarehouseId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("KS.Entities.TaxClass", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Interest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TaxClasses");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreationDate = new DateTime(2021, 6, 10, 0, 23, 28, 590, DateTimeKind.Local).AddTicks(9721),
                            Interest = 0m,
                            Name = "0%"
                        },
                        new
                        {
                            Id = 2L,
                            CreationDate = new DateTime(2021, 6, 10, 0, 23, 28, 590, DateTimeKind.Local).AddTicks(9781),
                            Interest = 10m,
                            Name = "10%"
                        },
                        new
                        {
                            Id = 3L,
                            CreationDate = new DateTime(2021, 6, 10, 0, 23, 28, 590, DateTimeKind.Local).AddTicks(9788),
                            Interest = 18m,
                            Name = "18%"
                        });
                });

            modelBuilder.Entity("KS.Entities.Warehouse", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Vendor")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Warehouses");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Address = "г. Белебей, ул. Красноармейская 125",
                            CreationDate = new DateTime(2021, 6, 10, 0, 23, 28, 591, DateTimeKind.Local).AddTicks(4294),
                            Name = "Основной",
                            Vendor = "452000"
                        },
                        new
                        {
                            Id = 2L,
                            Address = "г. Уфа, ул. Советская 25",
                            CreationDate = new DateTime(2021, 6, 10, 0, 23, 28, 591, DateTimeKind.Local).AddTicks(4321),
                            Name = "Основной (запасной)",
                            Vendor = "450000"
                        });
                });

            modelBuilder.Entity("KS.Entities.WishList", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProductId");

                    b.ToTable("WishLists");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = "fab4fac1-c546-41de-aebc-a14da6895711",
                            ConcurrencyStamp = "1",
                            Name = "Admin",
                            NormalizedName = "Admin"
                        },
                        new
                        {
                            Id = "c7b013f0-5201-4317-abd8-c211f91b7330",
                            ConcurrencyStamp = "2",
                            Name = "User",
                            NormalizedName = "User"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = "b74ddd14-6340-4840-95c2-db12554843e5",
                            RoleId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("KS.Entities.CartItem", b =>
                {
                    b.HasOne("KS.Entities.ApplicationUser", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId");

                    b.HasOne("KS.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("KS.Entities.Product", b =>
                {
                    b.HasOne("KS.Entities.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId");

                    b.HasOne("KS.Entities.TaxClass", "TaxClass")
                        .WithMany()
                        .HasForeignKey("TaxClassId");

                    b.Navigation("Brand");

                    b.Navigation("TaxClass");
                });

            modelBuilder.Entity("KS.Entities.ProductCategory", b =>
                {
                    b.HasOne("KS.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KS.Entities.Product", "Product")
                        .WithMany("Categories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("KS.Entities.Stock", b =>
                {
                    b.HasOne("KS.Entities.Order", null)
                        .WithMany("Stock")
                        .HasForeignKey("OrderId");

                    b.HasOne("KS.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KS.Entities.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("KS.Entities.WishList", b =>
                {
                    b.HasOne("KS.Entities.ApplicationUser", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId");

                    b.HasOne("KS.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("KS.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("KS.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KS.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("KS.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KS.Entities.Order", b =>
                {
                    b.Navigation("Stock");
                });

            modelBuilder.Entity("KS.Entities.Product", b =>
                {
                    b.Navigation("Categories");
                });
#pragma warning restore 612, 618
        }
    }
}
